In [61]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [62]:
from sklearn.datasets import load_diabetes

In [63]:
diabetes = load_diabetes()

In [64]:
diabetes

{'data': array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
          0.01990749, -0.01764613],
        [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
         -0.06833155, -0.09220405],
        [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
          0.00286131, -0.02593034],
        ...,
        [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
         -0.04688253,  0.01549073],
        [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
          0.04452873, -0.02593034],
        [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
         -0.00422151,  0.00306441]], shape=(442, 10)),
 'target': array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310., 101.,
         69., 179., 185., 118., 171., 166., 144.,  97., 168.,  68.,  49.,
         68., 245., 184., 202., 137.,  85., 131., 283., 129.,  59., 341.,
         87.,  65., 102., 265., 276., 252.,  90., 100.,  55.,  61.,  92.,
        259.,  53., 190., 142.,  75., 142., 155., 225.,  59., 104., 182.,
        128.,  52.,  37., 170., 170.,  61., 144.,  52., 128.,  71., 163.,
        150.,  97., 160., 178.,  48., 270., 202., 111.,  85.,  42., 170.,
        200., 252., 113., 143.,  51.,  52., 210.,  65., 141.,  55., 134.,
         42., 111.,  98., 164.,  48.,  96.,  90., 162., 150., 279.,  92.,
         83., 128., 102., 302., 198.,  95.,  53., 134., 144., 232.,  81.,
        104.,  59., 246., 297., 258., 229., 275., 281., 179., 200., 200.,
        173., 180.,  84., 121., 161.,  99., 109., 115., 268., 274., 158.,
        107.,  83., 103., 272.,  85., 280., 336., 281., 118., 317., 235.,
         60., 174., 259., 178., 128.,  96., 126., 288.,  88., 292.,  71.,
        197., 186.,  25.,  84.,  96., 195.,  53., 217., 172., 131., 214.,
         59.,  70., 220., 268., 152.,  47.,  74., 295., 101., 151., 127.,
        237., 225.,  81., 151., 107.,  64., 138., 185., 265., 101., 137.,
        143., 141.,  79., 292., 178.,  91., 116.,  86., 122.,  72., 129.,
        142.,  90., 158.,  39., 196., 222., 277.,  99., 196., 202., 155.,
         77., 191.,  70.,  73.,  49.,  65., 263., 248., 296., 214., 185.,
         78.,  93., 252., 150.,  77., 208.,  77., 108., 160.,  53., 220.,
        154., 259.,  90., 246., 124.,  67.,  72., 257., 262., 275., 177.,
         71.,  47., 187., 125.,  78.,  51., 258., 215., 303., 243.,  91.,
        150., 310., 153., 346.,  63.,  89.,  50.,  39., 103., 308., 116.,
        145.,  74.,  45., 115., 264.,  87., 202., 127., 182., 241.,  66.,
         94., 283.,  64., 102., 200., 265.,  94., 230., 181., 156., 233.,
         60., 219.,  80.,  68., 332., 248.,  84., 200.,  55.,  85.,  89.,
         31., 129.,  83., 275.,  65., 198., 236., 253., 124.,  44., 172.,
        114., 142., 109., 180., 144., 163., 147.,  97., 220., 190., 109.,
        191., 122., 230., 242., 248., 249., 192., 131., 237.,  78., 135.,
        244., 199., 270., 164.,  72.,  96., 306.,  91., 214.,  95., 216.,
        263., 178., 113., 200., 139., 139.,  88., 148.,  88., 243.,  71.,
         77., 109., 272.,  60.,  54., 221.,  90., 311., 281., 182., 321.,
         58., 262., 206., 233., 242., 123., 167.,  63., 197.,  71., 168.,
        140., 217., 121., 235., 245.,  40.,  52., 104., 132.,  88.,  69.,
        219.,  72., 201., 110.,  51., 277.,  63., 118.,  69., 273., 258.,
         43., 198., 242., 232., 175.,  93., 168., 275., 293., 281.,  72.,
        140., 189., 181., 209., 136., 261., 113., 131., 174., 257.,  55.,
         84.,  42., 146., 212., 233.,  91., 111., 152., 120.,  67., 310.,
         94., 183.,  66., 173.,  72.,  49.,  64.,  48., 178., 104., 132.,
        220.,  57.]),
 'frame': None,
 'DESCR': '.. _diabetes_dataset:\n\nDiabetes dataset\n----------------\n\nTen baseline variables, age, sex, body mass index, average blood\npressure, and six blood serum measurements were obtained for each of n =\n442 diabetes patients, as well as the response of interest, a\nquantitative measure of disease progression one year after baseline.\n\n**Data Set Characteristics:**\n\n:Number of Instances: 442\n\n:Number of Attributes: First 10 columns are numeric predictive values\n\n:Target: Column 11 is a quantitative measure of disease progression one year after baseline\n\n:Attribute Information:\n    - age     age in years\n    - sex\n    - bmi     body mass index\n    - bp      average blood pressure\n    - s1      tc, total serum cholesterol\n    - s2      ldl, low-density lipoproteins\n    - s3      hdl, high-density lipoproteins\n    - s4      tch, total cholesterol / HDL\n    - s5      ltg, possibly log of serum triglycerides level\n    - s6      glu, blood sugar level\n\nNote: Each of these 10 feature variables have been mean centered and scaled by the standard deviation times the square root of `n_samples` (i.e. the sum of squares of each column totals 1).\n\nSource URL:\nhttps://www4.stat.ncsu.edu/~boos/var.select/diabetes.html\n\nFor more information see:\nBradley Efron, Trevor Hastie, Iain Johnstone and Robert Tibshirani (2004) "Least Angle Regression," Annals of Statistics (with discussion), 407-499.\n(https://web.stanford.edu/~hastie/Papers/LARS/LeastAngle_2002.pdf)\n',
 'feature_names': ['age',
  'sex',
  'bmi',
  'bp',
  's1',
  's2',
  's3',
  's4',
  's5',
  's6'],
 'data_filename': 'diabetes_data_raw.csv.gz',
 'target_filename': 'diabetes_target.csv.gz',
 'data_module': 'sklearn.datasets.data'}

In [65]:
diabetes.feature_names

['age', 'sex', 'bmi', 'bp', 's1', 's2', 's3', 's4', 's5', 's6']

In [69]:
diabetes.data

array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
         0.01990749, -0.01764613],
       [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
        -0.06833155, -0.09220405],
       [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
         0.00286131, -0.02593034],
       ...,
       [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
        -0.04688253,  0.01549073],
       [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
         0.04452873, -0.02593034],
       [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
        -0.00422151,  0.00306441]], shape=(442, 10))

In [70]:
df = pd.DataFrame(diabetes.data, columns=diabetes.feature_names)

In [71]:
df['target'] = diabetes.target

To predict the disease progression one year after the baseline

In [72]:
df

,age,sex,bmi,bp,s1,s2,s3,s4,s5,s6,target
0,0.038076,0.050680,0.061696,0.021872,-0.044223,-0.034821,-0.043401,-0.002592,0.019907,-0.017646,151.0
1,-0.001882,-0.044642,-0.051474,-0.026328,-0.008449,-0.019163,0.074412,-0.039493,-0.068332,-0.092204,75.0
2,0.085299,0.050680,0.044451,-0.005670,-0.045599,-0.034194,-0.032356,-0.002592,0.002861,-0.025930,141.0
3,-0.089063,-0.044642,-0.011595,-0.036656,0.012191,0.024991,-0.036038,0.034309,0.022688,-0.009362,206.0
4,0.005383,-0.044642,-0.036385,0.021872,0.003935,0.015596,0.008142,-0.002592,-0.031988,-0.046641,135.0
...,...,...,...,...,...,...,...,...,...,...,...
437,0.041708,0.050680,0.019662,0.059744,-0.005697,-0.002566,-0.028674,-0.002592,0.031193,0.007207,178.0
438,-0.005515,0.050680,-0.015906,-0.067642,0.049341,0.079165,-0.028674,0.034309,-0.018114,0.044485,104.0
439,0.041708,0.050680,-0.015906,0.017293,-0.037344,-0.013840,-0.024993,-0.011080,-0.046883,0.015491,132.0
440,-0.045472,-0.044642,0.039062,0.001215,0.016318,0.015283,-0.028674,0.026560,0.044529,-0.025930,220.0
441,-0.045472,-0.044642,-0.073030,-0.081413,0.083740,0.027809,0.173816,-0.039493,-0.004222,0.003064,57.0

In [73]:
x = df.drop('target', axis = 1)
y = df['target']

In [74]:
from sklearn.model_selection import train_test_split

In [75]:
X_train, X_test, Y_train, Y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [76]:
X_train

,age,sex,bmi,bp,s1,s2,s3,s4,s5,s6
17,0.070769,0.050680,0.012117,0.056301,0.034206,0.049416,-0.039719,0.034309,0.027364,-0.001078
66,-0.009147,0.050680,-0.018062,-0.033213,-0.020832,0.012152,-0.072854,0.071210,0.000272,0.019633
137,0.005383,-0.044642,0.049840,0.097615,-0.015328,-0.016345,-0.006584,-0.002592,0.017036,-0.013504
245,-0.027310,-0.044642,-0.035307,-0.029770,-0.056607,-0.058620,0.030232,-0.039493,-0.049872,-0.129483
31,-0.023677,-0.044642,-0.065486,-0.081413,-0.038720,-0.053610,0.059685,-0.076395,-0.037129,-0.042499
...,...,...,...,...,...,...,...,...,...,...
106,-0.096328,-0.044642,-0.076264,-0.043542,-0.045599,-0.034821,0.008142,-0.039493,-0.059471,-0.083920
270,0.005383,0.050680,0.030440,0.083844,-0.037344,-0.047347,0.015505,-0.039493,0.008641,0.015491
348,0.030811,-0.044642,-0.020218,-0.005670,-0.004321,-0.029497,0.078093,-0.039493,-0.010903,-0.001078
435,-0.012780,-0.044642,-0.023451,-0.040099,-0.016704,0.004636,-0.017629,-0.002592,-0.038460,-0.038357
102,-0.092695,-0.044642,0.028284,-0.015999,0.036958,0.024991,0.056003,-0.039493,-0.005142,-0.001078

In [77]:

X_test

,age,sex,bmi,bp,s1,s2,s3,s4,s5,s6
287,0.045341,-0.044642,-0.006206,-0.015999,0.125019,0.125198,0.019187,0.034309,0.032432,-0.005220
211,0.092564,-0.044642,0.036907,0.021872,-0.024960,-0.016658,0.000779,-0.039493,-0.022517,-0.021788
72,0.063504,0.050680,-0.004050,-0.012556,0.103003,0.048790,0.056003,-0.002592,0.084492,-0.017646
321,0.096197,-0.044642,0.051996,0.079265,0.054845,0.036577,-0.076536,0.141322,0.098648,0.061054
73,0.012648,0.050680,-0.020218,-0.002228,0.038334,0.053174,-0.006584,0.034309,-0.005142,-0.009362
...,...,...,...,...,...,...,...,...,...,...
255,0.001751,-0.044642,-0.065486,-0.005670,-0.007073,-0.019476,0.041277,-0.039493,-0.003301,0.007207
90,0.012648,-0.044642,-0.025607,-0.040099,-0.030464,-0.045155,0.078093,-0.076395,-0.072133,0.011349
57,-0.027310,-0.044642,-0.063330,-0.050427,-0.089630,-0.104340,0.052322,-0.076395,-0.056153,-0.067351
391,-0.023677,-0.044642,-0.069797,-0.064199,-0.059359,-0.050478,0.019187,-0.039493,-0.089133,-0.050783
24,-0.063635,-0.044642,0.035829,-0.022885,-0.030464,-0.018850,-0.006584,-0.002592,-0.025953,-0.054925

In [78]:
Y_test

287    219.0
211     70.0
72     202.0
321    230.0
73     111.0
       ...
255    153.0
90      98.0
57      37.0
391     63.0
24     184.0
Name: target, Length: 89, dtype: float64

In [79]:
Y_train

17     144.0
66     150.0
137    280.0
245    125.0
31      59.0
       ...
106    134.0
270    202.0
348    148.0
435     64.0
102    302.0
Name: target, Length: 353, dtype: float64

In [80]:
X_train.shape, X_test.shape, Y_test.shape, Y_train.shape

((353, 10), (89, 10), (89,), (353,))

In [81]:
#Scaling

In [82]:
from sklearn.preprocessing import StandardScaler

In [83]:
scaler = StandardScaler()

In [84]:
scaler

StandardScaler()

In [85]:
x_train = scaler.fit_transform(X_train)

In [86]:
x_test = scaler.transform(X_test)

In [87]:
x_train

array([[ 1.49836523,  1.06136988,  0.21990201, ...,  0.71103773,
         0.54748197, -0.06144896],
       [-0.22885822,  1.06136988, -0.41936607, ...,  1.4842858 ,
        -0.01975653,  0.36723647],
       [ 0.08518241, -0.94217861,  1.01898711, ..., -0.06221033,
         0.3312366 , -0.31866022],
       ...,
       [ 0.63475351, -0.94217861, -0.46502808, ..., -0.83545839,
        -0.25375196, -0.06144896],
       [-0.30736838, -0.94217861, -0.53352109, ..., -0.06221033,
        -0.83072436, -0.83308273],
       [-2.03459183, -0.94217861,  0.56236706, ..., -0.83545839,
        -0.13312789, -0.06144896]], shape=(353, 10))

In [88]:
x_test

array([[ 9.48794133e-01, -9.42178611e-01, -1.68225039e-01,
        -3.54924745e-01,  2.63158584e+00,  2.64916600e+00,
         4.29486950e-01,  7.11037735e-01,  6.53600610e-01,
        -1.47186045e-01],
       [ 1.96942617e+00, -9.42178611e-01,  7.45015079e-01,
         4.27541124e-01, -5.11434037e-01, -3.33282444e-01,
         3.76314490e-02, -8.35458386e-01, -4.96908703e-01,
        -4.90134388e-01],
       [ 1.34134492e+00,  1.06136988e+00, -1.22563033e-01,
        -2.83791484e-01,  2.17022512e+00,  1.04272578e+00,
         1.21319795e+00, -6.22103255e-02,  1.74360703e+00,
        -4.04397302e-01],
       [ 2.04793633e+00, -9.42178611e-01,  1.06464912e+00,
         1.61333258e+00,  1.16099856e+00,  7.85958692e-01,
        -1.60816166e+00,  2.95345711e+00,  2.04001396e+00,
         1.22460733e+00],
       [ 2.42202722e-01,  1.06136988e+00, -4.65028077e-01,
        -7.03917017e-02,  8.14978020e-01,  1.13489858e+00,
        -1.19110751e-01,  7.11037735e-01, -1.33127889e-01,
        -2.32923131e-01],
       [ 1.63692565e-01, -9.42178611e-01, -5.56352089e-01,
        -5.68324528e-01,  2.08371999e+00,  1.99737263e+00,
         1.52668235e+00, -6.22103255e-02, -4.73432816e-01,
         1.10025212e-01],
       [-2.28858219e-01,  1.06136988e+00,  3.57605945e+00,
         2.85274603e-01,  6.41967752e-01,  7.26704750e-01,
        -4.32595152e-01,  7.11037735e-01,  6.79175966e-01,
         6.24447726e-01],
       [-5.42898847e-01,  1.06136988e+00,  9.27663103e-01,
         4.27541124e-01,  2.31440035e+00,  1.88544851e+00,
         3.76314490e-02,  7.11037735e-01,  1.52793425e+00,
         1.22460733e+00],
       [-2.03459183e+00,  1.06136988e+00, -1.94904327e+00,
        -1.20852388e+00, -5.11434037e-01, -6.22968386e-01,
        -1.19110751e-01, -6.22103255e-02,  4.78199472e-01,
         2.42881262e-02],
       [-1.32800041e+00,  1.06136988e+00,  2.88395020e-01,
        -4.26058006e-01,  7.86142975e-01,  1.02955823e+00,
         4.29486950e-01, -6.22103255e-02, -6.69256067e-01,
        -6.14489594e-02],
       [-9.35449631e-01, -9.42178611e-01, -7.39000113e-01,
        -4.97191267e-01,  9.87988288e-01,  8.91299035e-01,
         1.21319795e+00, -5.26159162e-01, -5.68863250e-01,
        -8.33082730e-01],
       [ 8.51824081e-02, -9.42178611e-01, -1.26411318e+00,
        -4.97191267e-01, -1.40532042e+00, -1.41960472e+00,
        -1.13793505e+00, -6.22103255e-02,  8.72708886e-01,
        -1.77619067e+00],
       [-1.95608167e+00, -9.42178611e-01, -1.33260619e+00,
        -5.68324528e-01, -1.14580502e+00, -1.12991878e+00,
         8.99713551e-01, -1.60870645e+00, -1.99230360e+00,
        -1.17603107e+00],
       [ 3.99223035e-01,  1.06136988e+00,  2.65564017e-01,
         1.28114025e+00,  3.24782260e-01,  4.43602580e-01,
        -9.81192854e-01,  7.11037735e-01,  9.51534425e-01,
         1.82476692e+00],
       [-3.07368376e-01,  1.06136988e+00, -1.21845117e+00,
        -7.03917017e-02, -5.69104126e-01, -5.96633300e-01,
         4.29486950e-01, -8.35458386e-01, -3.82583043e-01,
         8.81658983e-01],
       [-7.78429317e-01,  1.06136988e+00,  8.29159937e-02,
        -1.41524963e-01, -1.52066060e+00, -1.30109684e+00,
        -1.19110751e-01, -8.35458386e-01, -9.76542064e-01,
         6.24447726e-01],
       [ 8.70283977e-01,  1.06136988e+00,  1.47560717e+00,
         1.43008081e-01,  8.14978020e-01,  3.51429780e-01,
        -3.54224052e-01,  7.11037735e-01,  1.51152021e+00,
         1.73902984e+00],
       [ 1.34134492e+00,  1.06136988e+00,  1.84090322e+00,
         1.42340678e+00,  4.40122439e-01,  8.05710006e-01,
        -1.05956395e+00,  1.48428580e+00,  5.87944471e-01,
         1.48181858e+00],
       [-6.99919160e-01,  1.06136988e+00,  5.62367056e-01,
         1.42340678e+00, -2.64522735e+00, -2.22940861e+00,
        -1.13793505e+00, -1.01330544e+00, -6.69256067e-01,
         2.81499383e-01],
       [ 1.02730429e+00,  1.06136988e+00,  1.20163514e+00,
         1.42340678e+00,  2.95947215e-01,  4.50186351e-01,
        -4.32595152e-01,  7.11037735e-01,  4.35255777e-01,
         5.38710640e-01],
       [-1.56353089e+00, -9.42178611e-01,  7.90677085e-01,
        -7.10591049e-01, -2.51918634e-01, -7.08557414e-01,
        -5.10966252e-01, -6.22103255e-02,  1.39280475e+00,
        -3.18660216e-01],
       [ 1.02730429e+00, -9.42178611e-01, -9.44479139e-01,
        -1.13739061e+00,  9.59153244e-01,  1.06906086e+00,
         7.42971351e-01, -6.22103255e-02, -5.68863250e-01,
        -1.34750524e+00],
       [-9.35449631e-01, -9.42178611e-01, -1.08146516e+00,
        -7.81724310e-01, -1.36578455e-01, -4.58374101e-01,
         1.84016675e+00, -8.35458386e-01, -1.41762153e+00,
         1.10025212e-01],
       [ 1.26283476e+00,  1.06136988e+00,  4.48212041e-01,
         9.96607211e-01,  3.53617305e-01,  2.65840752e-01,
        -2.75852952e-01, -6.22103255e-02,  8.02472087e-01,
         3.67236469e-01],
       [-1.32800041e+00, -9.42178611e-01,  9.04832100e-01,
        -4.26058006e-01, -1.94248545e-01, -1.42353074e-01,
         5.07858050e-01, -8.35458386e-01, -5.93484302e-01,
        -2.32923131e-01],
       [ 8.70283977e-01,  1.06136988e+00,  2.65564017e-01,
         8.54340690e-01, -6.26774216e-01, -1.06776462e-02,
        -9.02821753e-01, -6.22103255e-02, -7.21551945e-01,
         2.81499383e-01],
       [ 6.34753506e-01,  1.06136988e+00,  1.22446614e+00,
         1.13887373e+00, -4.53763947e-01,  4.19925249e-02,
        -6.67708453e-01, -6.22103255e-02, -5.44623920e-01,
        -4.04397302e-01],
       [ 7.91773820e-01,  1.06136988e+00, -4.19366071e-01,
         1.35227352e+00, -1.05929989e+00, -3.33282444e-01,
        -1.60816166e+00,  7.11037735e-01, -2.74555792e-01,
        -3.18660216e-01],
       [-1.24949026e+00, -9.42178611e-01, -1.60657822e+00,
        -1.06625735e+00, -5.11434037e-01, -9.71908270e-01,
         1.99690895e+00, -1.60870645e+00, -1.30634964e+00,
        -1.00455690e+00],
       [ 3.20712879e-01,  1.06136988e+00, -4.87859080e-01,
        -2.12658223e-01,  7.28472886e-01,  1.02297446e+00,
         3.76314490e-02, -6.22103255e-02, -2.95741348e-01,
         4.52973554e-01],
       [ 5.56243349e-01, -9.42178611e-01,  1.93222723e+00,
        -1.11391664e+00,  1.80607036e-01,  8.51796406e-01,
        -5.89337353e-01,  4.32668433e-01, -1.03799926e+00,
         3.67236469e-01],
       [-2.27012230e+00, -9.42178611e-01, -8.30324124e-01,
        -5.68324528e-01,  6.52668576e-02,  4.37018808e-01,
         2.72744750e-01, -6.22103255e-02, -1.45617543e+00,
        -5.75871473e-01],
       [-7.18379055e-02,  1.06136988e+00,  2.65564017e-01,
        -1.56419018e+00,  6.52668576e-02,  1.47332867e-01,
        -2.75852952e-01, -6.22103255e-02,  3.76470629e-01,
         2.42881262e-02],
       [ 5.56243349e-01,  1.06136988e+00, -1.68225039e-01,
         5.69807646e-01, -3.38423768e-01, -1.72614176e-02,
        -1.21630615e+00,  7.11037735e-01,  5.87944471e-01,
         6.24447726e-01],
       [ 2.04793633e+00, -9.42178611e-01,  8.13508088e-01,
        -1.20852388e+00,  9.59153244e-01,  1.29290909e+00,
        -4.32595152e-01,  7.49700138e-01,  2.37333056e-01,
         4.52973554e-01],
       [-1.72055120e+00,  1.06136988e+00,  1.61259319e+00,
         1.06774047e+00,  1.65119432e+00,  1.37191435e+00,
         5.86229150e-01, -6.22103255e-02,  8.26138834e-01,
        -2.32923131e-01],
       [-2.28858219e-01,  1.06136988e+00, -6.93338107e-01,
        -5.68324528e-01, -2.23083590e-01, -4.09387485e-03,
        -4.32595152e-01, -6.22103255e-02,  1.04493892e-01,
         5.38710640e-01],
       [-7.18379055e-02,  1.06136988e+00, -7.39000113e-01,
        -4.02584030e-01,  6.70802797e-01,  9.17634120e-01,
        -2.75852952e-01,  4.09470991e-01,  1.88663535e-01,
         5.38710640e-01],
       [ 1.41985507e+00,  1.06136988e+00, -6.93338107e-01,
         7.18748201e-02,  5.26627573e-01,  7.66207378e-01,
        -5.89337353e-01,  7.11037735e-01,  4.63884907e-01,
         1.65329275e+00],
       [ 3.99223035e-01, -9.42178611e-01, -1.26411318e+00,
        -1.20852388e+00, -2.12382766e-02, -2.47693416e-01,
         1.60505345e+00, -8.35458386e-01, -1.30634964e+00,
        -1.60471650e+00],
       [-7.18379055e-02, -9.42178611e-01, -1.51525421e+00,
        -2.83791484e-01,  7.59676815e-03, -1.75271931e-01,
         1.52668235e+00, -8.35458386e-01, -1.34280407e+00,
         7.95921897e-01],
       [ 1.41985507e+00,  1.06136988e+00, -6.70507104e-01,
         1.16234771e+00,  7.59676815e-03, -3.13531130e-01,
         1.60505345e+00, -1.06743280e+00, -8.30724361e-01,
         1.10025212e-01],
       [ 8.70283977e-01,  1.06136988e+00, -5.10690083e-01,
         5.69807646e-01, -1.37648538e+00, -9.32405641e-01,
        -1.29467725e+00, -6.22103255e-02,  3.44479536e-02,
        -1.17603107e+00],
       [ 2.36197696e+00,  1.06136988e+00, -7.39000113e-01,
        -4.97191267e-01, -7.89083660e-02,  4.43602580e-01,
        -1.29467725e+00,  1.48428580e+00,  3.00508004e-01,
         8.81658983e-01],
       [ 8.70283977e-01, -9.42178611e-01, -9.90141145e-01,
         6.88600192e-01,  9.30318199e-01, -3.13531130e-01,
         8.21342451e-01, -3.09649705e-01,  1.85678752e+00,
         1.10025212e-01],
       [-3.85878533e-01, -9.42178611e-01, -7.84662118e-01,
        -5.68324528e-01,  6.99637841e-01,  3.77764866e-01,
         2.15365115e+00, -8.35458386e-01, -1.49549276e+00,
        -1.69045359e+00],
       [-2.11310198e+00, -9.42178611e-01, -8.07493121e-01,
        -1.56419018e+00, -7.99784484e-01, -5.63714443e-01,
         3.51115850e-01, -8.35458386e-01, -1.57679949e+00,
        -6.14489594e-02],
       [ 6.34753506e-01, -9.42178611e-01, -1.10429616e+00,
        -7.03917017e-02, -9.15124663e-01, -1.87388495e+00,
         2.54550666e+00, -1.60870645e+00, -4.04722904e-01,
         2.42881262e-02],
       [-4.64388690e-01, -9.42178611e-01, -1.83488825e+00,
        -5.68324528e-01, -7.42114394e-01, -7.01973643e-01,
         8.99713551e-01, -1.09063025e+00, -1.75029202e+00,
        -1.00455690e+00],
       [-1.32800041e+00, -9.42178611e-01, -8.40801808e-03,
        -6.39457789e-01, -1.36578455e-01, -4.38622787e-01,
         2.72744750e-01, -6.22103255e-02,  6.40622071e-01,
        -1.17603107e+00],
       [ 8.51824081e-02, -9.42178611e-01,  1.20163514e+00,
        -9.23990832e-01, -1.52066060e+00, -1.50519375e+00,
         4.29486950e-01, -1.60870645e+00, -1.10174679e+00,
        -5.75871473e-01],
       [-2.11310198e+00, -9.42178611e-01, -1.51525421e+00,
        -1.42192366e+00, -3.96093858e-01, -2.08190788e-01,
         3.51115850e-01, -8.35458386e-01, -1.00707980e+00,
        -1.69045359e+00],
       [ 5.56243349e-01,  1.06136988e+00,  3.34057026e-01,
        -7.10591049e-01, -1.36578455e-01,  9.83471834e-01,
        -1.37304835e+00,  1.48428580e+00, -2.04459948e+00,
        -1.26176816e+00],
       [ 3.99223035e-01, -9.42178611e-01, -8.98817133e-01,
        -3.54924745e-01, -1.65413500e-01, -3.53033759e-01,
         1.13482685e+00, -8.35458386e-01, -6.69256067e-01,
         2.42881262e-02],
       [-1.17098010e+00,  1.06136988e+00, -4.19366071e-01,
         1.63680656e+00,  1.88187467e+00,  2.28047480e+00,
        -8.24450653e-01,  2.25753386e+00,  7.29563235e-01,
        -9.18819816e-01],
       [-6.21409003e-01, -9.42178611e-01,  1.33862116e+00,
        -7.03917017e-02, -5.11434037e-01, -3.46449987e-01,
         5.07858050e-01, -8.35458386e-01, -1.30634964e+00,
        -1.34750524e+00],
       [-5.42898847e-01, -9.42178611e-01, -1.01297215e+00,
        -7.10591049e-01,  6.99637841e-01,  7.79374921e-01,
         8.21342451e-01, -6.22103255e-02, -7.21551945e-01,
         1.95762298e-01],
       [ 7.91773820e-01,  1.06136988e+00,  1.27012815e+00,
         4.27541124e-01, -9.15124663e-01, -7.15141185e-01,
        -9.02821753e-01, -6.22103255e-02,  3.91357777e-01,
        -4.04397302e-01],
       [-6.21409003e-01, -9.42178611e-01, -4.19366071e-01,
        -8.52857571e-01, -5.00733213e-02, -2.21358331e-01,
         8.21342451e-01, -8.35458386e-01, -2.12716871e-01,
        -1.17603107e+00],
       [-8.56939474e-01, -9.42178611e-01, -1.19562017e+00,
        -1.63532344e+00, -6.84444305e-01, -1.80146347e+00,
         3.01573326e+00, -1.60870645e+00, -4.27435347e-01,
        -1.47186045e-01],
       [-5.42898847e-01, -9.42178611e-01,  6.08029062e-01,
        -1.41524963e-01,  1.73769945e+00,  1.95128623e+00,
        -3.54224052e-01,  1.48428580e+00,  6.66388288e-01,
         2.42881262e-02],
       [-9.35449631e-01, -9.42178611e-01,  8.36339091e-01,
        -5.68324528e-01, -6.55609260e-01, -6.22968386e-01,
        -7.46079553e-01,  5.37768835e-02,  6.79175966e-01,
        -4.04397302e-01],
       [-1.32800041e+00,  1.06136988e+00,  1.11031113e+00,
        -4.26058006e-01, -1.03046484e+00, -1.01141090e+00,
         5.07858050e-01, -8.35458386e-01, -9.46386047e-01,
        -1.47186045e-01],
       [ 3.20712879e-01,  1.06136988e+00, -9.90141145e-01,
         1.28114025e+00,  2.38277126e-01,  9.07366794e-03,
         1.36994015e+00, -8.35458386e-01, -6.69256067e-01,
         7.10184811e-01],
       [-9.35449631e-01, -9.42178611e-01, -1.42393020e+00,
        -8.52857571e-01, -1.07743411e-01,  3.18510923e-01,
        -9.02821753e-01,  7.11037735e-01,  1.21671370e-01,
        -3.18660216e-01],
       [ 1.57687539e+00, -9.42178611e-01,  3.56888029e-01,
         1.28114025e+00,  1.30517378e+00,  9.17634120e-01,
         1.94373649e-01, -6.22103255e-02,  1.18972879e+00,
        -1.26176816e+00],
       [-1.17098010e+00,  1.06136988e+00, -2.82380054e-01,
         1.13887373e+00,  1.18983360e+00,  1.54967617e+00,
        -8.24450653e-01,  1.48428580e+00,  6.14474132e-01,
        -1.47186045e-01],
       [ 1.10581445e+00,  1.06136988e+00, -5.56352089e-01,
         1.13887373e+00, -1.36578455e-01, -8.96829030e-02,
        -4.32595152e-01, -6.22103255e-02,  5.33930845e-01,
        -8.33082730e-01],
       [-2.34863245e+00, -9.42178611e-01, -7.61831115e-01,
        -1.42192366e+00, -1.31881529e+00, -1.46569112e+00,
         1.94373649e-01, -8.35458386e-01, -3.82700371e-02,
        -1.69045359e+00],
       [-1.48502073e+00,  1.06136988e+00, -3.05211056e-01,
        -8.52857571e-01, -3.09588724e-01,  1.14414010e-01,
        -1.21630615e+00,  7.11037735e-01,  3.76470629e-01,
        -7.47345644e-01],
       [-1.64204104e+00,  1.06136988e+00, -4.19366071e-01,
         1.43008081e-01, -3.96093858e-01, -5.04460501e-01,
        -1.37304835e+00,  7.11037735e-01,  1.38402515e+00,
        -4.04397302e-01],
       [-7.18379055e-02,  1.06136988e+00,  6.08029062e-01,
         1.06774047e+00,  8.43813065e-01,  1.20732006e+00,
        -8.24450653e-01,  1.48428580e+00,  5.06256019e-01,
         5.38710640e-01],
       [ 1.26283476e+00, -9.42178611e-01, -4.87859080e-01,
         1.77907308e+00,  9.59153244e-01,  6.80618350e-01,
        -9.81192854e-01,  1.48428580e+00,  1.63118998e+00,
         2.76787487e+00],
       [-1.32800041e+00,  1.06136988e+00, -2.59549051e-01,
        -3.31450769e-01, -1.03046484e+00, -4.78125415e-01,
        -1.21630615e+00,  3.24413705e-01, -2.33138983e-01,
        -7.47345644e-01],
       [ 1.41985507e+00, -9.42178611e-01, -1.33260619e+00,
        -8.52857571e-01, -5.40269081e-01, -4.97876729e-01,
         7.42971351e-01, -8.35458386e-01, -1.20118531e+00,
        -1.26176816e+00],
       [ 1.63692565e-01,  1.06136988e+00, -8.75986130e-01,
         5.69807646e-01,  8.14978020e-01,  1.56284372e+00,
        -1.52979055e+00,  2.25753386e+00,  3.00508004e-01,
        -1.00455690e+00],
       [-6.21409003e-01,  1.06136988e+00,  1.24729714e+00,
         9.96607211e-01,  1.79536954e+00,  1.83277834e+00,
        -4.07396512e-02,  7.11037735e-01,  7.66208522e-01,
         9.67396068e-01],
       [-1.01395979e+00, -9.42178611e-01,  7.90677085e-01,
         7.41559207e-04,  3.53617305e-01,  3.38262238e-01,
        -5.89337353e-01,  5.48655642e-01,  9.06872981e-01,
        -5.75871473e-01],
       [ 9.48794133e-01,  1.06136988e+00,  3.79719032e-01,
         7.83207429e-01,  4.40122439e-01,  5.62110465e-01,
         1.94373649e-01, -6.22103255e-02, -9.45739932e-02,
         3.67236469e-01],
       [ 2.42202722e-01, -9.42178611e-01, -4.65028077e-01,
        -3.54924745e-01,  2.67112171e-01,  4.63353894e-01,
        -1.60816166e+00,  2.25753386e+00,  1.22828268e+00,
        -4.90134388e-01],
       [-1.87757151e+00, -9.42178611e-01, -1.22563033e-01,
        -2.12658223e-01, -5.00733213e-02,  1.80251724e-01,
         5.07858050e-01, -8.35458386e-01, -1.30634964e+00,
        -3.18660216e-01],
       [-1.24949026e+00, -9.42178611e-01, -2.82380054e-01,
        -7.10591049e-01, -9.72794752e-01, -9.85075812e-01,
         1.16002549e-01, -8.35458386e-01, -1.92485619e-01,
        -1.86192776e+00],
       [-1.09246994e+00, -9.42178611e-01, -1.40109920e+00,
        -2.13325627e+00, -5.00733213e-02, -3.06947359e-01,
         1.36994015e+00, -9.97840479e-01, -7.21551945e-01,
        -1.17603107e+00],
       [-6.21409003e-01, -9.42178611e-01, -1.30977519e+00,
        -6.39457789e-01,  9.87988288e-01,  4.37018808e-01,
         2.62387776e+00, -8.35458386e-01, -1.10174679e+00,
        -2.32923131e-01],
       [ 6.67225129e-03, -9.42178611e-01, -1.42393020e+00,
        -1.41524963e-01, -1.36578455e-01, -3.92536387e-01,
         8.99713551e-01, -8.35458386e-01, -9.45739932e-02,
         1.10025212e-01],
       [ 2.42202722e-01, -9.42178611e-01, -5.79183092e-01,
        -8.52857571e-01, -6.26774216e-01, -9.32405641e-01,
         1.68342455e+00, -1.60870645e+00, -1.53576441e+00,
         1.95762298e-01],
       [-6.21409003e-01, -9.42178611e-01, -1.37826820e+00,
        -1.06625735e+00, -1.86668114e+00, -2.17673843e+00,
         1.13482685e+00, -1.60870645e+00, -1.20118531e+00,
        -1.43324233e+00],
       [-5.42898847e-01, -9.42178611e-01, -1.51525421e+00,
        -1.35079040e+00, -1.23231015e+00, -1.04432975e+00,
         4.29486950e-01, -8.35458386e-01, -1.89171993e+00,
        -1.09029399e+00],
       [-1.40651057e+00, -9.42178611e-01,  7.22184076e-01,
        -4.97191267e-01, -6.26774216e-01, -3.79368844e-01,
        -1.19110751e-01, -6.22103255e-02, -5.68863250e-01,
        -1.17603107e+00]])

In [89]:
from sklearn.linear_model import LinearRegression

In [90]:
model = LinearRegression()

In [91]:
model

LinearRegression()

In [92]:
model.fit(x_train, Y_train)

LinearRegression()

In [95]:
df

,age,sex,bmi,bp,s1,s2,s3,s4,s5,s6,target
0,0.038076,0.050680,0.061696,0.021872,-0.044223,-0.034821,-0.043401,-0.002592,0.019907,-0.017646,151.0
1,-0.001882,-0.044642,-0.051474,-0.026328,-0.008449,-0.019163,0.074412,-0.039493,-0.068332,-0.092204,75.0
2,0.085299,0.050680,0.044451,-0.005670,-0.045599,-0.034194,-0.032356,-0.002592,0.002861,-0.025930,141.0
3,-0.089063,-0.044642,-0.011595,-0.036656,0.012191,0.024991,-0.036038,0.034309,0.022688,-0.009362,206.0
4,0.005383,-0.044642,-0.036385,0.021872,0.003935,0.015596,0.008142,-0.002592,-0.031988,-0.046641,135.0
...,...,...,...,...,...,...,...,...,...,...,...
437,0.041708,0.050680,0.019662,0.059744,-0.005697,-0.002566,-0.028674,-0.002592,0.031193,0.007207,178.0
438,-0.005515,0.050680,-0.015906,-0.067642,0.049341,0.079165,-0.028674,0.034309,-0.018114,0.044485,104.0
439,0.041708,0.050680,-0.015906,0.017293,-0.037344,-0.013840,-0.024993,-0.011080,-0.046883,0.015491,132.0
440,-0.045472,-0.044642,0.039062,0.001215,0.016318,0.015283,-0.028674,0.026560,0.044529,-0.025930,220.0
441,-0.045472,-0.044642,-0.073030,-0.081413,0.083740,0.027809,0.173816,-0.039493,-0.004222,0.003064,57.0

In [93]:
model.coef_

array([  1.75375799, -11.51180908,  25.60712144,  16.82887167,
       -44.44885564,  24.64095356,   7.67697768,  13.1387839 ,
        35.16119521,   2.35136365])

In [94]:
model.intercept_

np.float64(153.73654390934846)

With 1 unit increase in the age the one year progession will increase by  1.75375799 on an average by keeping all the other features as constant

In [96]:
y_pred = model.predict(x_test)

In [97]:
y_pred

array([139.5475584 , 179.51720835, 134.03875572, 291.41702925,
       123.78965872,  92.1723465 , 258.23238899, 181.33732057,
        90.22411311, 108.63375858,  94.13865744, 168.43486358,
        53.5047888 , 206.63081659, 100.12925869, 130.66657085,
       219.53071499, 250.7803234 , 196.3688346 , 218.57511815,
       207.35050182,  88.48340941,  70.43285917, 188.95914235,
       154.8868162 , 159.36170122, 188.31263363, 180.39094033,
        47.99046561, 108.97453871, 174.77897633,  86.36406656,
       132.95761215, 184.53819483, 173.83220911, 190.35858492,
       124.4156176 , 119.65110656, 147.95168682,  59.05405241,
        71.62331856, 107.68284704, 165.45365458, 155.00975931,
       171.04799096,  61.45761356,  71.66672581, 114.96732206,
        51.57975523, 167.57599528, 152.52291955,  62.95568515,
       103.49741722, 109.20751489, 175.64118426, 154.60296242,
        94.41704366, 210.74209145, 120.2566205 ,  77.61585399,
       187.93203995, 206.49337474, 140.63167076, 105.59678023,
       130.70432536, 202.18534537, 171.13039501, 164.91423047,
       124.72472569, 144.81030894, 181.99635452, 199.41369642,
       234.21436188, 145.95665512,  79.86703276, 157.36941275,
       192.74412541, 208.89814032, 158.58722555, 206.02195855,
       107.47971675, 140.93598906,  54.82129332,  55.92573195,
       115.01180018,  78.95584188,  81.56087285,  54.37997256,
       166.2543518 ])

In [98]:
from sklearn.metrics import mean_squared_error, mean_absolute_error, root_mean_squared_error, r2_score

In [99]:
mean_absolute_error(Y_test, y_pred)

42.79409467959994

In [100]:
mean_absolute_error(Y_test, y_pred)

42.79409467959994

In [101]:
root_mean_squared_error(Y_test, y_pred)

53.85344583676593

In [102]:
r2_score(Y_test, y_pred)*100

45.26027629719195